# Generated by Django 5.0.1 on 2024-01-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_isbn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
